/**
 * Types for the `lpulga_webmessage` Dataverse table.
 *
 * Three layers:
 *   WebMessageEntity      — raw OData field names returned by /_api/lpulga_webmessages
 *   WebMessageCreateInput — shape of the POST body sent when creating a record
 *   WebMessage            — clean domain shape (includes PK, for future read operations)
 *   mapWebMessage()       — converts an entity to the domain type with safe defaults
 */

// ---------------------------------------------------------------------------
// Raw OData entity (field names exactly as Dataverse returns them)
// ---------------------------------------------------------------------------

export interface WebMessageEntity {
  /** Primary key — guid, auto-generated by Dataverse */
  lpulga_webmessageid: string;
  /** Sender's display name */
  lpulga_name: string | null;
  /** Sender's email address */
  lpulga_email: string | null;
  /** Full message body */
  lpulga_message: string | null;
}

// ---------------------------------------------------------------------------
// Create input (POST body)
// ---------------------------------------------------------------------------

/** Columns sent when creating a new Web Message record via the Power Pages Web API. */
export interface WebMessageCreateInput {
  /** Sender's display name (required) */
  lpulga_name: string;
  /** Sender's email address (required) */
  lpulga_email: string;
  /** Full message body (required) */
  lpulga_message: string;
}

// ---------------------------------------------------------------------------
// Domain type
// ---------------------------------------------------------------------------

/** Clean domain type for a submitted Web Message (e.g. for future read operations). */
export interface WebMessage {
  /** Dataverse record GUID — use as React key */
  id: string;
  name: string;
  email: string;
  message: string;
}

// ---------------------------------------------------------------------------
// Mapper
// ---------------------------------------------------------------------------

/**
 * Converts a raw Dataverse OData entity into the clean UI domain type.
 * Null/undefined fields fall back to empty strings so components never
 * receive null (guards against column-permission-silenced fields).
 */
export function mapWebMessage(entity: WebMessageEntity): WebMessage {
  return {
    id:      entity.lpulga_webmessageid,
    name:    entity.lpulga_name    ?? '',
    email:   entity.lpulga_email   ?? '',
    message: entity.lpulga_message ?? '',
  };
}
